title = "sammi_dev"
baseURL = "https://sammidev.codes/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Sammi Aldhi Yanto"
  description = "Sofware Engineer"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Sammi Aldhi Yanto | 2022"
    url = "https://github.com/SemmiDev/"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "CV"
    url = "/cv"
    weight = 1
  [[menu.main]]
    name = "EXPERIENCE"
    url = "/experience"
    weight = 2
  [[menu.main]]
    name = "CERT"
    url = "https://drive.google.com/drive/u/1/folders/1YofO6A6a3o2bLTxSryQ9S5czpkTA1B-A"
    weight = 3
  [[menu.main]]
    name = "SKILL"
    url = "/skill"
    weight = 4
  [[menu.main]]
    name = "YOUTUBE"
    url = "https://www.youtube.com/channel/UCf9eTh_WEnl2NV2ii-F2OZQ"
    weight = 5
  [[menu.main]]
    name = ""
    url = "/posts"
    weight = 6

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
